<?php 

use Calc\Model\Calculadora;
use Calc\Controller\CalculadoraController;
use Zend\Session\Container;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-05 at 14:09:17.
 * 
 * @group unidade
 * @small
 */
class CalculadoraControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CalculadoraController
     */
    private $calculadoraController;
    private $calculadora;
    private $container;
    
    
    protected function setUp() {
        $this->calculadora = new Calculadora();
        $this->container = new Container();
        $this->container->calculadora = $this->calculadora;
        $this->calculadoraController = new Calc\Controller\CalculadoraController($this->container);
    }
    
    /**
     * @test
     * @expectedException InvalidArgumentException
     */
    public function __construct_deveLancarExcecaoSeContainerForNull() {
        new CalculadoraController(NULL);
    }
    
    /**
     * @test
     */
    public function __construct_deveRestaurarCalculadoraDoContainer() {        
        self::assertSame($this->calculadora, $this->calculadoraController->getCalculadora());
    }
        
    /**
     * @test
     */
    public function __construct_deveInserirNovaCalculadoraNoContainerSeNaoPossuirUma() {
        $this->container->calculadora = NULL;
        $controller = new CalculadoraController($this->container);
        self::assertSame($this->calculadora, $this->container->calculadoraController->getCalculadora());        
    }
    
    /**
     * @test
     */
    public function teclaAction_deveTeclarNaCalculadora() {
        $calculadora = Phockito::mock('Calc\Model\Calculadora');
        $this->container->calculadora = $calculadora;
        $controller = new CalculadoraController($this->container);
        $controller->teclaAction();
    }
}
