<?php
// Generated by Zend Framework 2
return array(
    'Calc\Module'                           => __DIR__ . '/../../../../M:\testeunidade\module\Calc/M:/testeunidade/module/Calc/Module.php',
    'Calc\Controller\CalculadoraController' => __DIR__ . '/../../../../M:\testeunidade\module\Calc/M:/testeunidade/module/Calc/src/Calc/Controller/CalculadoraController.php',
    'Calc\Model\Calculadora'                => __DIR__ . '/../../../../M:\testeunidade\module\Calc/M:/testeunidade/module/Calc/src/Calc/Model/Calculadora.php',
    'CalcTest\Bootstrap'                    => __DIR__ . '/../../../../M:\testeunidade\module\Calc/M:/testeunidade/module/Calc/test/Bootstrap.php',
    'CalculadoraTest'                       => __DIR__ . '/../../../../M:\testeunidade\module\Calc/M:/testeunidade/module/Calc/test/src/CalcTest/Model/CalculadoraTest.php',
);