<?php 

use Calc\Model\Calculadora;
use Calc\Controller\CalculadoraController;
use Zend\Session\Container;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-05 at 14:09:17.
 */
class CalculadoraControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CalculadoraController
     */
    protected $calculadoraController;
    
    
    protected function setUp() {
        $this->calculadoraController = new Calc\Controller\CalculadoraController();        
    }
    
    /**
     * @test
     */
    public function getContainer_deveRetornarUmNovoContainerSeNenhumFoiInjetado() {                
        Assert\that($this->calculadoraController->getContainer())->notNull()->isInstanceOf('Zend\Session\Container');
    }
    
    /**
     * @test
     */
    public function getContainer_deveRetornarSempreOMesmoContainer() {
        $container = $this->calculadoraController->getContainer();
        Assert\that($this->calculadoraController->getContainer())->same($container);
        Assert\that($this->calculadoraController->getContainer())->same($container);
    }
    
    /**
     * @test
     */
    public function getContainer_deveRetornarContainerInjetadoNoSet() {
        $container = new Container();
        $this->calculadoraController->setContainer($container);        
        Assert\that($this->calculadoraController->getContainer())->same($container);
    }
    
    /**
     * @test
     */
    public function getContainer_deveRetornarNovoContainerSeSetForNull() {
        $container = $this->calculadoraController->getContainer();
        $this->calculadoraController->setContainer(NULL);
        Assert\that($this->calculadoraController->getContainer())->notNull()->isInstanceOf('Zend\Session\Container')->notSame($container);
    }
    
    /**
     * @test
     */
    public function estado_deveRestaurarCalculadoraAoTeclar() {        
        $container = Phockito::mock('Zend\Session\Container');
        Phockito::when($container->offsetGet('calculadora'))->return(Phockito::mock('Calc\Model\Calculadora'));
        $this->calculadoraController->setContainer($container);
        $this->calculadoraController->teclaAction();
        Phockito::verify($container)->offsetGet('calculadora');
    }
    
    
}
