<?php 

use Calc\Model\Calculadora;
use Calc\Controller\CalculadoraController;
use Zend\Session\Container;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-05 at 14:09:17.
 */
class CalculadoraControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CalculadoraController
     */
    private $calculadoraController;
    private $calculadora;
    private $container;
    
    
    protected function setUp() {
        $this->calculadora = new Calculadora();
        $this->container = new Container();
        $this->container->calculadora = $this->calculadora;
        $this->calculadoraController = new Calc\Controller\CalculadoraController($this->container);
    }
    
    /**
     * @test
     * @expectedException InvalidArgumentException
     */
    public function __construct_deveLancarExcecaoSeContainerForNull() {
        new CalculadoraController(NULL);
    }
    
    /**
     * @test
     */
    public function __construct_deveCriarUmaCalculadoraSeContainerNaoPossuirUma() {
        $this->container->calculadora = NULL;
        $controller = new CalculadoraController($this->container);
        Assert\that($controller->getCalculadora())->notNull()->notSame($this->calculadora);
    }
    
    /**
     * @test
     */
    public function getContainer_deveRetornarUmNovoContainerSeNenhumFoiInjetado() {                
        Assert\that($this->calculadoraController->getContainer())->notNull()->isInstanceOf('Zend\Session\Container');
    }
    
    /**
     * @test
     */
    public function getContainer_deveRetornarSempreOMesmoContainer() {
        $container = $this->calculadoraController->getContainer();
        Assert\that($this->calculadoraController->getContainer())->same($container);
        Assert\that($this->calculadoraController->getContainer())->same($container);
    }
    
    /**
     * @test
     */
    public function getContainer_deveRetornarContainerInjetadoNoSet() {
        $container = new Container();
        $this->calculadoraController->setContainer($container);        
        Assert\that($this->calculadoraController->getContainer())->same($container);
    }
        
    
    /**
     * @test
     */
    public function estado_deveRestaurarCalculadoraAoConstruir() {        
        Assert\that($this->calculadoraController->getCalculadora())->same($this->calculadora);
    }
        
    
    
}
